language: python

python:
  - '3.7-dev'
  - '3.6'
  - '3.6-dev'
  - '3.5'
  - '3.5-dev'
  - '3.4'
  - '3.3'

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - pip install -e .
  - pip install coveralls

script:
  - py.test -v --color=yes --cov pyrallel

after_success:
  - coveralls

notifications:
  email: false

deploy:
  - provider: pypi
    user: usc_isi_i2_admin
    password:
      secure: QwVcmGEN4dJN1vi7HM0E4ZIgGM/kCKWJ323AoXDUtSwbZIUYX5sZsNoh+buJzfJR94geZqckf9ABSk22cazuXzrDBUeh73sOReILcCciEMxYWkrBDrvtr2rBBq2GOC8B8Xc3BzNcZGG1pVhoNFjr6/Co0rOIn6JmxPRBLjCoyT33bQGHchuXPbozhMNDtG1+p+j5+lrGZetdD6sSl8O3BCOkJtfor50LvgxLoYcqcOd6jj9DgY9r6fo7if43xESj07UfneZ+Eo+xVQ9NRsItD4sc2toC5wPcdggqVQ+cy/mc9A3SAbD/Y36Jz6RX1hM5LrnPEDRi/URlmBriwf59VygwSXaypfaex8aEsx5W7CPuexNbRg/qWojoZASE9GzQcAw6aamWIzJy6EOvKI5NmGzVLDUqU3U5Ow/7vLhb/iQi+09Du+5bPSmR2qZvO+uyIHjW8ZGgZQ7Q4uldokYjwca8jUWvx5HrT0B1gJPjV0PjNFrwVuA40TvodoHQJ+Ief0cE9ALsBH6VLEAduC+lWOV1B/bvEBGUgAgD2l1Gb7QKpq1bl1izoGB6H3V0qqXnHdIstMC+0rYwD19FDXPxThrIpuwtsx2KsgXbeFL/wpcABd40rVgLRt6Ol/dBR60DzAGn+L5fV9ahPZY/UNYZwlblPbDsZDP4kUDXYrhW6T4=
    on:
      tags: true
